name: build-and-deploy

on:
  push:
    branches: [main]

env:
  ECR_REGISTRY: <ECR_REGISTRY>
  AWS_REGION: <AWS_REGION>
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}:${{ github.sha }}

      - name: Deploy Docker image to Amazon ECR
        run: |
          docker tag ${{ env.ECR_REGISTRY }}:${{ github.sha }} ${{ env.ECR_REGISTRY }}:latest
          docker push ${{ env.ECR_REGISTRY }}:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}:latest
